/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jjflix;

import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.Timer;
import javax.swing.SwingConstants;
import org.sikuli.api.DesktopScreenRegion;
import org.sikuli.api.ImageTarget;
import org.sikuli.api.ScreenRegion;
import org.sikuli.api.Target;
import org.sikuli.api.robot.Mouse;
import org.sikuli.api.robot.desktop.DesktopMouse;

/**
 *
 * @author KIMP
 */
public class NewJFrame extends javax.swing.JFrame {

    Mouse mouse = new DesktopMouse();
    ScreenRegion searchRegion = new DesktopScreenRegion(1100,420,480,400);
    
    List<Target> targets = new ArrayList<Target>();
    
    public NewJFrame() {
        initComponents();
        targetsToArray();
        lblStartStop.setHorizontalAlignment(SwingConstants.CENTER);
    }

    public void loopButton() {
        for(Target t: targets) {
            findButton(t);
        }
    }
    
    public void findButton(Target t) {
        try {
            ScreenRegion flix = searchRegion.find(t);
            mouse.click(flix.getCenter());
            System.out.println("Found");
        } catch(NullPointerException e) {
            System.out.println(e.getMessage());
        }
    }
    
    public void targetsToArray() {
        File jflx900 = new File("scrn\\jjflx900.png");
        File jflx900full = new File("scrn\\jjflx900full.png");
        File jflx1080 = new File("scrn\\jjflx1080.png");
        File jflx1080full = new File("scrn\\jjflx1080full.png");
        Target flixBtn900 = new ImageTarget(jflx900.getAbsoluteFile());
        Target flixBtn900Fullscreen = new ImageTarget(jflx900full.getAbsoluteFile());
        Target flixBtn1080 = new ImageTarget(jflx1080.getAbsoluteFile());
        Target flixBtn1080Fullscreen = new ImageTarget(jflx1080full.getAbsoluteFile());
        flixBtn900Fullscreen.setMinScore(0.7);
        flixBtn900.setMinScore(0.7);
        flixBtn1080.setMinScore(0.7);
        flixBtn1080Fullscreen.setMinScore(0.7);
        targets.add(flixBtn900);
        targets.add(flixBtn900Fullscreen);
        targets.add(flixBtn1080);
        targets.add(flixBtn1080Fullscreen);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnStart = new javax.swing.JButton();
        lblStartStop = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        lblStartStop.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblStartStop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(140, Short.MAX_VALUE)
                .addComponent(lblStartStop)
                .addGap(50, 50, 50)
                .addComponent(btnStart)
                .addGap(70, 70, 70))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        Timer timer = new Timer();
        
        if(btnStart.getText().equals("Start")) {
        timer.schedule(new checkUpdate(), 0, 10000);
        btnStart.setText("Stop");
        lblStartStop.setText("Started! ");
        } else if (btnStart.getText().equals("Stop")) {
        timer.cancel();
        btnStart.setText("Start");
        lblStartStop.setText("Stopped! ");
    }
    }//GEN-LAST:event_btnStartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel lblStartStop;
    // End of variables declaration//GEN-END:variables
}
